version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "8765:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "9500:8000"
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - database
    networks:
      - default
volumes:
  data: