http:
  port: 8000
env: "local"
hashsalt: salt
jwtsignkey: key
migrationspath: path
smtp:
  host: host
  port: port
  password: pass
  from: from
postgres:
  host: "database"
  port: "5432"
  password: password
  username: username
  dbname: dbname
  sslmode: "disable"
bot:
  token: token
templatespath: "./templates"