basePath: /api
definitions:
  http_1_1.dataResponse:
    properties:
      data: {}
    type: object
  http_1_1.dataWithPaginationResponse:
    type: object
  http_1_1.errorResponse:
    properties:
      error:
        type: string
    type: object
  http_1_1.metaParams:
    type: object
  http_1_1.signInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  http_1_1.signUpInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  http_1_1.signUpWithEmailInput:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  models.Category:
    properties:
      category_id:
        type: integer
      color:
        type: string
      created_at:
        type: string
      name:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  models.CreateCategoryInput:
    properties:
      color:
        type: string
      name:
        type: string
    required:
    - name
    type: object
host: localhost:8000
info:
  contact: {}
  description: API for MLF application
  license:
    name: MIT
  title: My Local Financier API
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: returns auth JWT
      parameters:
      - description: info for user's login
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http_1_1.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_1_1.dataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
      summary: User sign-in with email and password
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: creates user and returns auth JWT
      parameters:
      - description: data for user creation
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http_1_1.signUpInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_1_1.dataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
      summary: User sign-up with name, email and password
      tags:
      - auth
  /auth/sign-up-with-email:
    post:
      consumes:
      - application/json
      description: creates user with email, password generates automatically and returns
        auth JWT
      parameters:
      - description: email for user creation
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http_1_1.signUpWithEmailInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_1_1.dataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
      summary: User sign-up with email only
      tags:
      - auth
  /category:
    get:
      consumes:
      - application/json
      description: returns user categories list with pagination
      parameters:
      - description: pagination params and filters
        in: body
        name: input
        schema:
          $ref: '#/definitions/http_1_1.metaParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_1_1.dataWithPaginationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get categories list
      tags:
      - category
    post:
      consumes:
      - application/json
      description: creates new category and returns it
      parameters:
      - description: created category fields
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateCategoryInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_1_1.dataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create new category
      tags:
      - category
  /category/{categoryId}:
    delete:
      consumes:
      - application/json
      description: delete existing category and returns id of deleted category
      parameters:
      - description: target category id
        in: path
        name: categoryId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_1_1.dataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete existing category
      tags:
      - category
    get:
      consumes:
      - application/json
      description: returns user's category object by id
      parameters:
      - description: target category id
        in: path
        name: categoryId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_1_1.dataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get category by id
      tags:
      - category
    put:
      consumes:
      - application/json
      description: updates existing category and returns updated instance
      parameters:
      - description: updated category fields
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Category'
      - description: target category id
        in: path
        name: categoryId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_1_1.dataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http_1_1.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update existing category
      tags:
      - category
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
